# Generated by Django 5.2.2 on 2025-06-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_appuserrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.appuserrole'),
        ),
    ]
