# Generated by Django 5.2.2 on 2025-06-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_remove_appuser_is_admin_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserrole',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
