# Generated by Django 5.2.2 on 2025-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_appuserrole_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserrole',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appuserrole',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
