# Generated by Django 5.2.2 on 2025-06-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_appuserrole_code_alter_appuserrole_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='created',
            new_name='created_at',
        ),
    ]
