# Generated by Django 5.2.2 on 2025-06-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userfamilyassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='area_code',
            field=models.IntegerField(default=157),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='family_code',
            field=models.IntegerField(default=157015006),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subfamily_code',
            field=models.IntegerField(default=157015006),
            preserve_default=False,
        ),
    ]
