# Generated by Django 5.2.2 on 2025-06-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_area_product_area_code_product_family_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='code',
            field=models.CharField(default='default', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
