# Generated by Django 5.2.2 on 2025-06-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_producttype_code_alter_producttype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
