# Generated by Django 5.2.2 on 2025-06-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('enabled', models.BooleanField(default=True)),
                ('sellable', models.BooleanField(default=True)),
                ('category_code', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('related', models.TextField(blank=True, null=True)),
                ('substitute', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_settings', to='core.product')),
            ],
            options={
                'unique_together': {('product', 'country_code')},
            },
        ),
    ]
