# Generated by Django 5.2.2 on 2025-06-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_appuserrole_code_alter_appuserrole_name'),
        ('core', '0009_productcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_by_type', to='core.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_by_status', to='core.status'),
        ),
        migrations.CreateModel(
            name='ProductWorkflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_entries', to='core.product')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_statuses', to='core.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_workflows', to='authapp.appuser')),
            ],
        ),
    ]
