# Generated by Django 5.2.2 on 2025-06-24 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_product_type_alter_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productworkflow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
