# Generated by Django 5.2.2 on 2025-06-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_productworkflow_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productworkflow',
            old_name='created',
            new_name='created_at',
        ),
    ]
