# Generated by Django 5.2.2 on 2025-06-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_created_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productworkflow',
            name='status',
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='new_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_new_statuses', to='core.status'),
        ),
        migrations.AddField(
            model_name='productworkflow',
            name='old_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_old_statuses', to='core.status'),
        ),
    ]
