# Generated by Django 5.2.2 on 2025-06-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_productworkflow_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=193, null=True),
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_url', models.URLField()),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='core.product')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('product', 'youtube_url')},
            },
        ),
    ]
